/*
 WAQTD EMPLOYEES NAME FROM EMPLOYEES TABLE ?
 */
SELECT ENAME FROM EMP;
 
/*
  WAQTD SAL AND EMPLOYEES NAME FROM EMPLOYEE TABLE ?
*/
SELECT SAL , ENAME FROM EMP;
  
/*
  WAQTD NAME AND DEPTNO AND JOBS THAT ARE PRESENT IN EMP TABLE ?
*/
SELECT ENAME , JOB , DEPTNO FROM EMP;

/*
WAQTD JOB  WITH DEPTNO FOR ALL THE EMPLOYEES USING ALIAS AS DESIGNATION FOR THE JOB AND DNO FOR THE DEPTNO ?
*/
SELECT JOB "DESIGNATION",DEPTNO "DNO" FROM EMP;

/*
WAQTD JOB AS DESIGNATION HIREDATE AS JOINING DATE MGR AS   REPORTING MANAGER NUMBER FOR ALL THE EMPLOYEES 
*/
SELECT JOB "DESIGNATION" ,HIREDATE "JOININGDATE" ,MGR "REPORTING MANAGER NUMBER" FROM EMP;
