/*
 WAQTD EMPLOYEES NAME FROM EMPLOYEES TABLE ?
 */
SELECT ENAME FROM EMP;
 
/*
  WAQTD SAL AND EMPLOYEES NAME FROM EMPLOYEE TABLE ?
*/
SELECT SAL , ENAME FROM EMP;
  
/*
  WAQTD NAME AND DEPTNO AND JOBS THAT ARE PRESENT IN EMP TABLE ?
*/
SELECT ENAME , JOB , DEPTNO FROM EMP;

/*
WAQTD JOB  WITH DEPTNO FOR ALL THE EMPLOYEES USING ALIAS AS DESIGNATION FOR THE JOB AND DNO FOR THE DEPTNO ?
*/
SELECT JOB "DESIGNATION",DEPTNO "DNO" FROM EMP;

/*
WAQTD JOB AS DESIGNATION HIREDATE AS JOINING DATE MGR AS   REPORTING MANAGER NUMBER FOR ALL THE EMPLOYEES 
*/
SELECT JOB "DESIGNATION" ,HIREDATE "JOININGDATE" ,MGR "REPORTING MANAGER NUMBER" FROM EMP;

/*
 WAQTD ALL THE DETAILS OF AN EMPLOYEES ALONG WITH 12% HIKE IN ANNUAL SALARY WITH ALIAS NAME FOR ALL THE EMPLOYEES
*/
SELECT EMP.* , (SAL+SAL*12/100)*12 FROM EMP;

/*
 WAQTD ANNAUL SALARY  AND HALF_TERM SALARY WITH ALIAS NAME FOR ALL THE EMPLOYEES ?
 */
 SELECT SAL*12 "ANNUALSAL" ,SAL*6 "HALF_TERM" FROM EMP;
 
 /*
  WAQTD TOTAL SALARY NEEDED TO PAY FOR EACH AND EVERY EMPLOYEE ?
  */
  SELECT ENAME,SAL FROM EMP;
