CREATE DATABASE college;
USE college;
DROP TABLE STUDENT;
CREATE TABLE STUDENT
(
    STUDENT_ID INT PRIMARY KEY,
    STUDENT_NAME VARCHAR(15),
    GENDER VARCHAR(6),
    DEPARTMENT VARCHAR(15),
    YEAR_OF_STUDY INT,
    MARKS INT,
    CITY VARCHAR(15),
    ADMDATE DATE
);

INSERT INTO STUDENT VALUES (101, 'AMIT',   'MALE',   'COMPUTER',    1, 78, 'DELHI',       DATE '2023-07-01');
INSERT INTO STUDENT VALUES (102, 'RIYA',   'FEMALE', 'COMPUTER',    2, 85, 'MUMBAI',      DATE '2022-06-15');
INSERT INTO STUDENT VALUES (103, 'KARAN',  'MALE',   'MECHANICAL',  3, 65, 'PUNE',        DATE '2021-08-20');
INSERT INTO STUDENT VALUES (104, 'NEHA',   'FEMALE', 'ELECTRICAL',  4, 90, 'DELHI',       DATE '2020-07-10');
INSERT INTO STUDENT VALUES (105, 'RAHUL',  'MALE',   'COMPUTER',    2, 55, 'CHENNAI',     DATE '2022-06-18');
INSERT INTO STUDENT VALUES (106, 'SNEHA',  'FEMALE', 'MECHANICAL',  1, 88, 'BANGALORE',   DATE '2023-07-05');
INSERT INTO STUDENT VALUES (107, 'ARJUN',  'MALE',   'ELECTRICAL',  3, 72, 'HYDERABAD',   DATE '2021-08-25');
INSERT INTO STUDENT VALUES (108, 'POOJA',  'FEMALE', 'COMPUTER',    4, 95, 'MUMBAI',      DATE '2020-07-12');
INSERT INTO STUDENT VALUES (109, 'VIKAS',  'MALE',   'CIVIL',       2, 60, 'JAIPUR',      DATE '2022-06-22');
INSERT INTO STUDENT VALUES (110, 'ANJALI', 'FEMALE', 'CIVIL',       1, 82, 'DELHI',       DATE '2023-07-08');
INSERT INTO STUDENT VALUES (111, 'ROHIT',  'MALE',   'COMPUTER',    3, 68, 'NOIDA',       DATE '2021-08-18');
INSERT INTO STUDENT VALUES (112, 'KAVYA',  'FEMALE', 'ELECTRICAL',  2, 91, 'CHENNAI',     DATE '2022-06-10');
INSERT INTO STUDENT VALUES (113, 'MOHIT',  'MALE',   'MECHANICAL',  4, 74, 'PUNE',        DATE '2020-07-20');
INSERT INTO STUDENT VALUES (114, 'NIDHI',  'FEMALE', 'COMPUTER',    1, 89, 'GURGAON',     DATE '2023-07-02');
INSERT INTO STUDENT VALUES (115, 'SANJAY', 'MALE',   'CIVIL',       3, 58, 'BHOPAL',      DATE '2021-08-30');
INSERT INTO STUDENT VALUES (116, 'PRIYA',  'FEMALE', 'MECHANICAL',  2, 76, 'INDORE',     DATE '2022-06-25'); 

SELECT * FROM STUDENT;

COMMIT;

-- 1. Display student information exactly as stored
SELECT *
FROM STUDENT;

-- 2. Display all columns and MARKS + 5 as BONUS_MARKS
SELECT *, MARKS + 5 AS BONUS_MARKS
FROM STUDENT;

-- 3. Display all student details and MARKS * 2 as DOUBLE_MARKS
SELECT *, MARKS * 2 AS DOUBLE_MARKS
FROM STUDENT;

-- 4. Display all columns along with YEAR_OF_STUDY + 1 as NEXT_YEAR
SELECT *, YEAR_OF_STUDY + 1 AS NEXT_YEAR
FROM STUDENT;

-- 5. Display all student details and MARKS / 10 as MARKS_RATIO
SELECT *, MARKS / 10 AS MARKS_RATIO
FROM STUDENT;

-- 6. Display complete STUDENT table and MARKS + 10 as UPDATED_MARKS
SELECT *, MARKS + 10 AS UPDATED_MARKS
FROM STUDENT;