CREATE DATABASE college;
USE college;
DROP TABLE STUDENT;
CREATE TABLE STUDENT
(
    STUDENT_ID INT PRIMARY KEY,
    STUDENT_NAME VARCHAR(15),
    GENDER VARCHAR(6),
    DEPARTMENT VARCHAR(15),
    YEAR_OF_STUDY INT,
    MARKS INT,
    CITY VARCHAR(15),
    ADMDATE DATE
);